// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnaqcsjummrfdwdmppkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYXFjc2p1bW1yZmR3ZG1wcGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NDI1MjMsImV4cCI6MjA3ODIxODUyM30.2XQXXGxEBQib2Mr1RTIbpud5ezIzWB_bNUfV9_g43FE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});